# Generated by Django 5.2.7 on 2025-10-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('passwordHash', models.CharField(max_length=255)),
                ('Role', models.CharField(default='Player', max_length=20)),
                ('ControlTimestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PinCode', models.CharField(max_length=10, unique=True)),
                ('Difficulty', models.IntegerField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='Python_app.category')),
            ],
            options={
                'db_table': 'game_session',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Difficulty', models.IntegerField()),
                ('TimeLimit', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Python_app.category')),
            ],
            options={
                'db_table': 'quiz_question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('IsCorrect', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Python_app.quizquestion')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Python_app.gamesession')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Python_app.user')),
            ],
            options={
                'db_table': 'player_score',
                'unique_together': {('Session', 'User')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmitTimestamp', models.DateTimeField(auto_now_add=True)),
                ('IsCorrect', models.BooleanField()),
                ('ReactionTime', models.IntegerField(blank=True, null=True)),
                ('Answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_selections', to='Python_app.answer')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_responses', to='Python_app.gamesession')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_responses', to='Python_app.quizquestion')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Python_app.user')),
            ],
            options={
                'db_table': 'player_answer',
                'unique_together': {('Question', 'User', 'Session')},
            },
        ),
    ]
